// file for the main entry point in a Node.js application 
// used to configure and start a web server
// contains core logic for listening for network request, processing and sending response back to client (frontend)
require("dotenv").config();

const express = require("express");
const cors = require("cors");
const path = require("path");
const connectDB = require("./config/db");

const authRoutes = require("./routes/authRoutes");
const userRoutes = require("./routes/userRoutes");
const jobRoutes = require("./routes/jobRoutes");
const applicationRoutes = require("./routes/applicationRoutes");
const savedJobsRoutes = require("./routes/savedJobsRoutes");
const analyticsRoutes = require("./routes/analyticsRoutes");

const app = express();

// middleware to handle CORS 
// app.use(
//     cors({
//         origin: '*',
//         methods: ["GET", "POST", "PUT", "DELETE"],
//         allowedHeaders: ["Content-Type", "Authorization"],
//     })
// );


// app.use(cors({
//   origin: [
//     "http://localhost:5173", // local dev
//     "https://job-your-love-job-portal-app-front.onrender.com/" // frontend origin link generated by Render
//   ],
//   methods: ["GET", "POST", "PUT", "DELETE"],
//   allowedHeaders: ["Content-Type", "Authorization"],
//   credentials: true
// }));

const allowedOrigins = [
  "http://localhost:5173", // local dev frontend
  "https://job-your-love-job-portal-app-front.onrender.com" //  deployed frontend
];
app.use(cors({
  origin: function(origin, callback) {
    // allow requests with no origin (like Postman)
    if (!origin) return callback(null, true);
    if (allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(new Error("Not allowed by CORS"));
    }
  },
  methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
  allowedHeaders: ["Content-Type", "Authorization"],
  credentials: true
}));

// connect database 
connectDB();

// middleware
app.use(express.json());

// routes 
app.use("/api/auth", authRoutes);
app.use("/api/user", userRoutes);
app.use("/api/jobs", jobRoutes);
app.use("/api/application", applicationRoutes);
app.use("/api/save-jobs", savedJobsRoutes);
app.use("/api/analytics", analyticsRoutes);

// serve upload folders
app.use("/uploads", express.static(path.join(__dirname, "uploads"), {}));

// start server 
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}...`));

